In [2]:
import pandas as pd
import numpy as np

In [3]:
df= pd.read_csv('Results.csv')

In [4]:
df.head()

                Race  Year                Name Gender  Age  Finish Age Bracket
0  Columbus Marathon  2015      Becky Williams      F   29   13645    Under 35
1  Columbus Marathon  2015     Jessica Sheahan      F   27   13648    Under 35
2  Columbus Marathon  2015        Kelsey Stief      F   27   13650    Under 35
3  Columbus Marathon  2015        Mehgan Cline      F   26   13650    Under 35
4  Columbus Marathon  2015  Stefanie Driesenga      F   28   13652    Under 35

In [7]:
df.shape

(2053366, 7)

In [12]:
df.describe()

               Year           Age        Finish
count  2.053366e+06  2.053366e+06  2.053366e+06
mean   2.014416e+03  3.919313e+01  1.651780e+04
std    2.833053e+00  1.207902e+01  3.366605e+03
min    2.010000e+03 -9.000000e+00  7.425000e+03
25%    2.012000e+03  3.100000e+01  1.408000e+04
50%    2.014000e+03  3.900000e+01  1.613500e+04
75%    2.017000e+03  4.800000e+01  1.855300e+04
max    2.019000e+03  1.160000e+02  7.346000e+04

In [13]:
df.isna().sum()

Race           0
Year           0
Name           2
Gender         8
Age            0
Finish         0
Age Bracket    0
dtype: int64